apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: "3.9.1"
    helm:
      values: |
        global:
          extraEnvVars:
            - name: AWS_REGION
              value: ap-south-1
            - name: AWS_DEFAULT_REGION
              value: ap-south-1
        admissionController:
          replicas: 1
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          rbac:
            serviceAccount:
              annotations:
                eks.amazonaws.com/role-arn: arn:aws:iam::316899785097:role/leviathan-kyverno-ecr
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
        backgroundController:
          replicas: 1
        cleanupController:
          replicas: 1
        reportsController:
          replicas: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
