apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: leviathan-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/Naveenbana5250/Project-Leviathan.git
    targetRevision: main
    path: gitops/policies
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
