apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-etl
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    repoURL: https://github.com/Naveenbana5250/Project-Leviathan.git
    targetRevision: main
    path: gitops/data/spark
  destination:
    server: https://kubernetes.default.svc
    namespace: neo4j
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
